name: Unity Build MAC

on:
    workflow_dispatch:
        inputs:
            customParameters:
                description: "build custom parameters"
                required: false
                default: ""

### Refer to https://game.ci/docs/github/getting-started
jobs:
    buildForMac:
        name: Build for StandaloneOSX
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-StandaloneOSX
            - uses: game-ci/unity-builder@v3
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: StandaloneOSX
                  customParameters: "${{ inputs.customParameters }}"
            - uses: actions/upload-artifact@v3
              with:
                  name: Build-StandaloneOSX
                  path: build
